//
//  ListInteractor.swift
//  WhereIsMyApple
//
//  Created by Raymond Law on 1/8/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol ListBusinessLogic
{
  func fetchStores(request: List.FetchStores.Request)
  func locateStore(request: List.LocateStore.Request)
}

protocol ListDataStore
{
}

class ListInteractor: ListBusinessLogic, ListDataStore
{
  enum DependencyInjection
  {
    case method, extractAndOverrideCall
  }
  
  let dependencyInjection = DependencyInjection.extractAndOverrideCall
  
  var presenter: ListPresentationLogic?
  var worker: ListWorker?
  
  var stores: [Store] = [
    Store(name: "Clarendon", address: "2700 Clarendon Boulevard, Arlington, VA 22201", phone: "(703) 236-7970", hours: "Mon - Sat 10:00 a.m. - 9:00 p.m., Sun 11:00 a.m. - 6:00 p.m."),
    Store(name: "Pentagon City", address: "1100 South Hayes Street, Arlington, VA 22202", phone: "(703) 236-1550", hours: "Mon - Sat 10:00 a.m. - 9:30 p.m., Sun 11:00 a.m. - 6:00 p.m."),
    Store(name: "Fair Oaks", address: "11750 Fair Oaks, Fairfax, VA 22033", phone: "(703) 251-7400", hours: "Mon - Sat 10:00 a.m. - 9:30 p.m., Sun 11:00 a.m. - 6:00 p.m."),
    Store(name: "Tysons Corner", address: "1961 Chain Bridge Road, McLean, VA 22102", phone: "(703) 336-8450", hours: "Mon - Sat 10:00 a.m. - 9:30 p.m., Sun 11:00 a.m. - 7:00 p.m."),
    Store(name: "MacArthur Center", address: "300 Monticello Avenue, Norfolk, VA 23510", phone: "(757) 628-8400", hours: "Mon - Sat 10:00 a.m. - 9:00 p.m., Sun 11:00 a.m. - 6:00 p.m."),
    Store(name: "Reston", address: "11949 Market Street, Reston, VA 20190", phone: "(571) 449-4800", hours: "Mon - Sat 10:00 a.m. - 9:00 p.m., Sun 11:00 a.m. - 6:00 p.m."),
    Store(name: "Short Pump Town Center", address: "11800 W. Broad Street, Richmond, VA 23233", phone: "(804) 420-3000", hours: "Mon - Sat 10:00 a.m. - 9:00 p.m., Sun 11:00 a.m. - 6:00 p.m."),
    Store(name: "Lynnhaven Mall", address: "701 Lynnhaven Parkway, Virginia Beach, VA 23452", phone: "(757) 306-2480", hours: "Mon - Sat 10:00 a.m. - 9:00 p.m., Sun 11:00 a.m. - 6:00 p.m."),
    Store(name: "Potomac Town Center", address: "15100 Potomac Town Place, Woodbridge, VA 22191", phone: "(703) 986-2030", hours: "Mon - Sat 10:00 a.m. - 9:00 p.m., Sun 11:00 a.m. - 6:00 p.m.")
  ]
  
  // MARK: Fetch stores
  
  func fetchStores(request: List.FetchStores.Request)
  {
    let response = List.FetchStores.Response(stores: stores)
    presenter?.presentFetchStores(response: response)
  }
  
  // MARK: Locate store
  
  var geocoder = CLGeocoder()
  
  func locateStore(request: List.LocateStore.Request)
  {
    geocoder.geocodeAddressString(request.address) { (placemarks, error) in
      if let placemark = placemarks?.first {
        if let addressDictionary = placemark.addressDictionary as? [String : Any], let coordinate = placemark.location?.coordinate {
          let response = List.LocateStore.Response(name: request.name, coordinate: coordinate, addressDictionary: addressDictionary)
          switch self.dependencyInjection
          {
          case .method:
            self.presenter?.presentLocateStoreAlt(response: response)
          case .extractAndOverrideCall:
            self.presenter?.presentLocateStore(response: response)
          }
        }
      }
    }
  }
}
