//
//  ListPresenter.swift
//  WhereIsMyApple
//
//  Created by Raymond Law on 1/8/18.
//  Copyright (c) 2018 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol ListPresentationLogic
{
  func presentFetchStores(response: List.FetchStores.Response)
  func presentLocateStore(response: List.LocateStore.Response)
  func presentLocateStoreAlt(response: List.LocateStore.Response)
}

class ListPresenter: ListPresentationLogic
{
  weak var viewController: ListDisplayLogic?
  
  // MARK: Fetch stores
  
  func presentFetchStores(response: List.FetchStores.Response)
  {
    let displayedStores = response.stores.map { List.DisplayedStore(name: $0.name, address: $0.address) }
    let viewModel = List.FetchStores.ViewModel(displayedStores: displayedStores)
    viewController?.displayFetchStores(viewModel: viewModel)
  }
  
  // MARK: Locate store
  
  func presentLocateStore(response: List.LocateStore.Response)
  {
    let viewModel = List.LocateStore.ViewModel(name: response.name, coordinate: response.coordinate, addressDictionary: response.addressDictionary)
    viewController?.displayLocateStore(viewModel: viewModel)
  }
  
  func presentLocateStoreAlt(response: List.LocateStore.Response)
  {
    let placemark = MKPlacemark(coordinate: response.coordinate, addressDictionary: response.addressDictionary)
    let mapItem = List.LocateStore.MapItem(placemark: placemark)
    mapItem.name = response.name
    
    let viewModel = List.LocateStoreAlt.ViewModel(mapItem: mapItem)
    viewController?.displayLocateStoreAlt(viewModel: viewModel)
  }
}
